#!/usr/bin/env python3
"""
分析推薦頁面的價格邏輯正確性
"""

print("=" * 80)
print("💰 價格邏輯分析報告")
print("=" * 80)
print()

# 模擬現有邏輯
print("## 📋 現有邏輯分析 (recommendation/page.tsx)")
print()

print("### 1. 價格計算方式 (line 239-247)")
print("```typescript")
print("const calculateTotal = () => {")
print("    return currentItems.reduce((sum, item) => {")
print("        // 只計算被評為「like」的菜品")
print("        if (itemRatings.get(item.name) === 'like') {")
print("            return sum + (item.price || 0);")
print("        }")
print("        return sum;")
print("    }, 0);")
print("};")
print("```")
print()

print("### 2. 顯示位置 (line 360-361, 409-413)")
print("```typescript")
print("const total = calculateTotal();")
print("const perPerson = Math.round(total / people);")
print()
print("// 顯示在頂部卡片")
print("<h1>NT$ {total.toLocaleString()}</h1>  // 預估總費用")
print("<p>NT$ {perPerson.toLocaleString()}</p>  // 人均約")
print("```")
print()

print("=" * 80)
print("🔍 問題診斷：邏輯是否正確？")
print("=" * 80)
print()

print("❌ **發現問題 1：初始狀態下總價為 0**")
print()
print("原因：")
print("  - calculateTotal() 只計算 itemRatings.get(item.name) === 'like' 的菜品")
print("  - 初始狀態下，itemRatings 是空的 Map")
print("  - 因此顯示「NT$ 0」而非「系統推薦的總金額」")
print()

print("影響：")
print("  ✗ 使用者看不到「系統建議如果全選要花多少錢」")
print("  ✗ 無法在選擇前預覽預算是否合理")
print()

print("❌ **發現問題 2：未區分「系統推薦」vs「當前已選」**")
print()
print("現況：")
print("  - 只有一個 total 變數")
print("  - 無法同時顯示兩個數字讓使用者比較")
print()

print("影響：")
print("  ✗ 使用者不知道「系統原本建議的總價」")
print("  ✗ 當換菜後，無法判斷是否超出原本預期")
print()

print("=" * 80)
print("✅ 正確的邏輯設計")
print("=" * 80)
print()

print("### 應該有兩個價格計算：")
print()
print("```typescript")
print("// 1. 系統推薦總金額（固定，不變）")
print("const systemRecommendedTotal = currentItems.reduce((sum, item) => ")
print("    sum + (item.price || 0), 0);")
print()
print("// 2. 當前已選總金額（動態變化）")
print("const currentSelectedTotal = currentItems.reduce((sum, item) => {")
print("    if (selectedItems.has(item.name)) {  // 使用 'selected' 而非 'like'")
print("        return sum + (item.price || 0);")
print("    }")
print("    return sum;")
print("}, 0);")
print("```")
print()

print("### 顯示方式建議：")
print()
print("#### 方案 A：並排顯示")
print("```")
print("┌────────────────────────────────────┐")
print("│ 系統推薦       │    已選中         │")
print("│ NT$ 1,200     │    NT$ 800       │")
print("│ 人均 $400     │    人均 $267     │")
print("└────────────────────────────────────┘")
print("```")
print()

print("#### 方案 B：動態切換（推薦）")
print("```")
print("初始狀態（未選任何菜）：")
print("┌────────────────────────────────────┐")
print("│ 系統建議總價                        │")
print("│ NT$ 1,200                          │")
print("│ 人均 $400 / 人（共 8 道菜）        │")
print("└────────────────────────────────────┘")
print()
print("選擇後：")
print("┌────────────────────────────────────┐")
print("│ 已選 3 道 · NT$ 800                │")
print("│ 人均 $267 / 人                     │")
print("│ 💡 系統建議: $1,200 (8道)          │")
print("└────────────────────────────────────┘")
print("```")
print()

print("=" * 80)
print("🎯 改良版方案的完整邏輯")
print("=" * 80)
print()

print("### State 設計")
print("```typescript")
print("// 改名：從 itemRatings 改為 selectedItems")
print("const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set());")
print()
print("// 新增：系統推薦總價（固定值，fetch 後設定）")
print("const [systemTotal, setSystemTotal] = useState(0);")
print("```")
print()

print("### 計算函數")
print("```typescript")
print("// 系統推薦總價（初始化時計算一次）")
print("useEffect(() => {")
print("    if (currentItems.length > 0) {")
print("        const total = currentItems.reduce((sum, item) => ")
print("            sum + (item.price || 0), 0);")
print("        setSystemTotal(total);")
print("    }")
print("}, [currentItems]);")
print()
print("// 當前已選總價（動態變化）")
print("const selectedTotal = Array.from(selectedItems).reduce((sum, itemName) => {")
print("    const item = currentItems.find(i => i.name === itemName);")
print("    return sum + (item?.price || 0);")
print("}, 0);")
print("```")
print()

print("### UI 顯示邏輯")
print("```typescript")
print("const selectedCount = selectedItems.size;")
print("const totalCount = currentItems.length;")
print("const hasSelection = selectedCount > 0;")
print()
print("return (")
print("    <div className='price-card'>")
print("        {hasSelection ? (")
print("            // 已選狀態")
print("            <>")
print("                <h3>已選 {selectedCount} 道 · NT$ {selectedTotal}</h3>")
print("                <p>人均 ${Math.round(selectedTotal / people)}</p>")
print("                <small>💡 系統建議: ${systemTotal} ({totalCount}道)</small>")
print("            </>")
print("        ) : (")
print("            // 初始狀態")
print("            <>")
print("                <h3>系統建議總價 NT$ {systemTotal}</h3>")
print("                <p>人均 ${Math.round(systemTotal / people)} ({totalCount}道)</p>")
print("            </>")
print("        )}")
print("    </div>")
print(");")
print("```")
print()

print("=" * 80)
print("📊 邏輯驗證案例")
print("=" * 80)
print()

# 模擬案例
print("### 案例：2人用餐，系統推薦 5 道菜")
print()

items = [
    {"name": "小籠包", "price": 180},
    {"name": "紅燒肉", "price": 280},
    {"name": "炒青菜", "price": 120},
    {"name": "蛋炒飯", "price": 150},
    {"name": "酸辣湯", "price": 100},
]

system_total = sum(item["price"] for item in items)
people = 2

print(f"系統推薦菜品：")
for item in items:
    print(f"  - {item['name']}: NT$ {item['price']}")
print()
print(f"系統推薦總價: NT$ {system_total}")
print(f"系統推薦人均: NT$ {system_total // people} / 人")
print()

print("--- 使用者操作流程 ---")
print()

# 步驟 1
print("步驟 1: 初始進入頁面")
print("  顯示: 「系統建議總價 NT$ 830 (人均 $415, 共 5 道菜)」")
print("  selectedItems = {}")
print()

# 步驟 2
selected = {"小籠包", "紅燒肉"}
selected_total = sum(item["price"] for item in items if item["name"] in selected)
print("步驟 2: 使用者點選「我要點這道」→ 小籠包、紅燒肉")
print(f"  顯示: 「已選 2 道 · NT$ {selected_total}」")
print(f"       「人均 ${selected_total // people} / 人」")
print(f"       「💡 系統建議: ${system_total} (5道)」")
print(f"  selectedItems = {selected}")
print()

# 步驟 3
print("步驟 3: 使用者點選「換一道」→ 將紅燒肉換成糖醋魚")
selected = {"小籠包", "糖醋魚"}
items_updated = items[:]
items_updated[1] = {"name": "糖醋魚", "price": 320}
selected_total = sum(item["price"] for item in items_updated if item["name"] in selected)
print(f"  顯示: 「已選 2 道 · NT$ {selected_total}」")
print(f"       「人均 ${selected_total // people} / 人」")
print(f"       「💡 系統建議: ${system_total} (5道)」")
print(f"  selectedItems = {selected}")
print("  註: 系統推薦總價可能改變（因為菜品變了），需重新計算")
print()

print("=" * 80)
print("✅ 結論")
print("=" * 80)
print()

print("您的邏輯**完全正確**！應該要：")
print()
print("1. ✅ 初始顯示「系統推薦總金額」")
print("   - 讓使用者知道「如果全選」要花多少錢")
print("   - 評估是否符合預算")
print()
print("2. ✅ 動態顯示「當前已選總金額」")
print("   - 使用者每次點選/取消/換菜時即時更新")
print("   - 保留「系統建議」作為參考基準")
print()
print("3. ✅ 兩者都應該顯示")
print("   - 系統建議 = 完整體驗的參考值")
print("   - 當前已選 = 實際要支付的金額")
print()

print("🔧 需要修正現有實作的地方：")
print()
print("  ❌ 目前只有「當前已選」（且初始為 0）")
print("  ✅ 應該加入「系統推薦」並優先顯示")
print()

print("=" * 80)
print("📝 實作建議優先級")
print("=" * 80)
print()
print("優先級 1 (必做): 修正初始顯示")
print("  - 加入 systemTotal 計算")
print("  - 初始顯示系統推薦總價")
print()
print("優先級 2 (必做): 動態切換顯示")
print("  - 選擇後切換為「已選總價」")
print("  - 保留系統建議作為小字提示")
print()
print("優先級 3 (建議): 增強視覺回饋")
print("  - 進度條顯示「已選/總數」")
print("  - 價格超預算時警告")
print()

print("=" * 80)
