#!/usr/bin/env python3
"""
候選菜品池設計：換菜邏輯的資料來源策略
"""

print("=" * 80)
print("🎲 候選菜品池設計方案")
print("=" * 80)
print()

print("## 🎯 核心原則")
print()
print("❌ 錯誤做法：換菜時從「整個餐廳菜單」隨機選擇")
print("✅ 正確做法：只能從「AI 預先推薦的候選池」中選擇")
print()
print("原因：")
print("  1. 確保推薦品質（每道菜都經過 AI 評估）")
print("  2. 避免推薦不適合的菜品（例如：使用者不吃辣，卻推薦麻辣鍋）")
print("  3. 控制價格範圍（候選池的菜品價格應該接近）")
print()

print("=" * 80)
print("📋 方案比較")
print("=" * 80)
print()

print("### 方案 A：輪播池（Rotation Pool）")
print()
print("```")
print("AI 一次推薦 3-5 道候選菜品，前端輪播")
print()
print("初始顯示：")
print("  熱菜：宮保雞丁 ($180)")
print()
print("候選池（隱藏）：")
print("  熱菜: [宮保雞丁, 糖醋魚, 紅燒肉]")
print()
print("換菜流程：")
print("  第1次換 → 糖醋魚 ($220)")
print("  第2次換 → 紅燒肉 ($280)")
print("  第3次換 → 宮保雞丁 (回到第一個)")
print("```")
print()
print("優點：")
print("  ✅ 前端實作簡單（不需呼叫 API）")
print("  ✅ 回應速度快（無網路延遲）")
print("  ✅ 候選池大小可控（3-5 道）")
print()
print("缺點：")
print("  ❌ 選擇有限（只有 3-5 個選項）")
print("  ❌ 初始載入量較大（需要預載所有候選菜品資料）")
print()

print("=" * 80)
print()

print("### 方案 B：動態取得（API Fetch）")
print()
print("```")
print("AI 只推薦 1 道顯示菜品，換菜時即時呼叫 API")
print()
print("初始顯示：")
print("  熱菜：宮保雞丁 ($180)")
print()
print("換菜流程：")
print("  點擊「換一道」")
print("    ↓")
print("  POST /api/recommendations/{id}/replace")
print("  { category: '熱菜', excluded: ['宮保雞丁'] }")
print("    ↓")
print("  回應：糖醋魚 ($220)")
print()
print("後端邏輯：")
print("  1. 從「該類別的候選池」中過濾")
print("  2. 排除已經被換掉的菜品")
print("  3. 根據評分返回最佳候選")
print("```")
print()
print("優點：")
print("  ✅ 初始載入輕量（只需顯示的菜品）")
print("  ✅ 可動態調整（根據使用者行為）")
print("  ✅ 候選池可以更大（10-20 道）")
print()
print("缺點：")
print("  ❌ 需要網路請求（有延遲）")
print("  ❌ 後端邏輯較複雜")
print()

print("=" * 80)
print()

print("### 方案 C：混合策略（推薦 ⭐）")
print()
print("```")
print("AI 推薦「1 道顯示 + 2-3 道備選」，前端先輪播，不夠時呼叫 API")
print()
print("初始推薦：")
print("  熱菜: {")
print("    display: 宮保雞丁 ($180),")
print("    alternatives: [糖醋魚 ($220), 紅燒肉 ($280)]")
print("  }")
print()
print("換菜流程：")
print("  第1次換 → 糖醋魚 (從 alternatives)")
print("  第2次換 → 紅燒肉 (從 alternatives)")
print("  第3次換 → 呼叫 API 取得更多候選")
print("```")
print()
print("優點：")
print("  ✅ 平衡速度與彈性")
print("  ✅ 初始載入量適中")
print("  ✅ 備選用完再呼叫 API")
print()
print("缺點：")
print("  ⚠️  實作略複雜（需要狀態管理）")
print()

print("=" * 80)
print("🏆 推薦方案：方案 C（混合策略）")
print("=" * 80)
print()

print("理由：")
print("  1. 大部分使用者只會換 1-2 次，備選池足夠")
print("  2. 少數使用者換很多次，可用 API 補充")
print("  3. 初始載入量不會過大")
print()

print("=" * 80)
print("📐 資料結構設計")
print("=" * 80)
print()

print("### API 回應格式（方案 C）")
print()
print("```json")
print("{")
print('  "recommendation_id": "abc123",')
print('  "items": [')
print("    {")
print('      "category": "熱菜",')
print('      "display": {')
print('        "name": "宮保雞丁",')
print('        "price": 180,')
print('        "reason": "香辣適中...",')
print('        "review_count": 234')
print("      },")
print('      "alternatives": [')
print("        {")
print('          "name": "糖醋魚",')
print('          "price": 220,')
print('          "reason": "酸甜可口...",')
print('          "review_count": 189')
print("        },")
print("        {")
print('          "name": "紅燒肉",')
print('          "price": 280,')
print('          "reason": "肥而不膩...",')
print('          "review_count": 312')
print("        }")
print("      ]")
print("    },")
print("    {")
print('      "category": "冷菜",')
print('      "display": {')
print('        "name": "涼拌黃瓜",')
print('        "price": 80,')
print('        "reason": "清爽開胃...",')
print('        "review_count": 156')
print("      },")
print('      "alternatives": [')
print("        {")
print('          "name": "皮蛋豆腐",')
print('          "price": 100,')
print('          "reason": "口感滑嫩...",')
print('          "review_count": 142')
print("        }")
print("      ]")
print("    }")
print("  ]")
print("}")
print("```")
print()

print("=" * 80)
print("💻 前端實作邏輯")
print("=" * 80)
print()

print("### State 設計")
print()
print("```typescript")
print("interface DishSlot {")
print("    category: string;")
print("    currentDish: MenuItem;  // 當前顯示的菜品")
print("    alternatives: MenuItem[];  // 備選菜品池")
print("    replacedDishes: string[];  // 已經換掉的菜名")
print("    status: 'pending' | 'selected';")
print("}")
print()
print("const [dishSlots, setDishSlots] = useState<DishSlot[]>([]);")
print("```")
print()

print("### 換菜邏輯")
print()
print("```typescript")
print("const handleReplaceDish = async (slotIndex: number) => {")
print("    const slot = dishSlots[slotIndex];")
print("    ")
print("    // 1. 先從備選池取得")
print("    if (slot.alternatives.length > 0) {")
print("        const nextDish = slot.alternatives[0];")
print("        ")
print("        setDishSlots(prev => prev.map((s, i) => {")
print("            if (i !== slotIndex) return s;")
print("            ")
print("            return {")
print("                ...s,")
print("                currentDish: nextDish,")
print("                alternatives: s.alternatives.slice(1),  // 移除第一個")
print("                replacedDishes: [...s.replacedDishes, s.currentDish.name]")
print("            };")
print("        }));")
print("    } else {")
print("        // 2. 備選池用完，呼叫 API")
print("        const newDish = await fetchReplacement(")
print("            slot.category,")
print("            slot.replacedDishes")
print("        );")
print("        ")
print("        setDishSlots(prev => prev.map((s, i) => {")
print("            if (i !== slotIndex) return s;")
print("            ")
print("            return {")
print("                ...s,")
print("                currentDish: newDish,")
print("                replacedDishes: [...s.replacedDishes, s.currentDish.name]")
print("            };")
print("        }));")
print("    }")
print("};")
print("```")
print()

print("=" * 80)
print("🔧 後端實作邏輯")
print("=" * 80)
print()

print("### 1. 初始推薦（generate_recommendations）")
print()
print("```python")
print("def generate_recommendations(restaurant_name, people, budget, dietary):")
print("    '''")
print("    生成初始推薦（1 顯示 + 2-3 備選）")
print("    '''")
print("    # 1. 取得餐廳資訊與評論")
print("    reviews = fetch_restaurant_reviews(restaurant_name)")
print("    ")
print("    # 2. 使用 AI 生成候選池（每個類別 4-5 道）")
print("    candidate_pools = {}")
print("    for category in ['冷菜', '熱菜', '主食', '湯品']:")
print("        candidates = ai_recommend_dishes(")
print("            category=category,")
print("            reviews=reviews,")
print("            people=people,")
print("            budget=budget,")
print("            dietary=dietary,")
print("            top_k=4  # 每類取 4 道")
print("        )")
print("        candidate_pools[category] = candidates")
print("    ")
print("    # 3. 分配顯示 vs 備選")
print("    recommendations = []")
print("    for category, candidates in candidate_pools.items():")
print("        recommendations.append({")
print("            'category': category,")
print("            'display': candidates[0],  # 第一道顯示")
print("            'alternatives': candidates[1:3]  # 第 2-3 道作為備選")
print("        })")
print("    ")
print("    return recommendations")
print("```")
print()

print("### 2. 換菜 API（replace_dish）")
print()
print("```python")
print("def replace_dish(recommendation_id, category, excluded_dishes):")
print("    '''")
print("    當備選池用完時，動態取得新候選")
print("    '''")
print("    # 1. 取得原始推薦的上下文")
print("    context = get_recommendation_context(recommendation_id)")
print("    ")
print("    # 2. 從候選池中過濾")
print("    candidate_pool = get_candidate_pool(")
print("        restaurant_name=context['restaurant'],")
print("        category=category")
print("    )")
print("    ")
print("    # 3. 排除已經顯示過的菜品")
print("    available = [")
print("        dish for dish in candidate_pool")
print("        if dish['name'] not in excluded_dishes")
print("    ]")
print("    ")
print("    # 4. 根據評分排序")
print("    available.sort(key=lambda x: x['rating'], reverse=True)")
print("    ")
print("    if not available:")
print("        return {'error': '該類別暫無其他推薦'}")
print("    ")
print("    return available[0]")
print("```")
print()

print("=" * 80)
print("🎯 候選池生成策略")
print("=" * 80)
print()

print("### 問題：如何決定每個類別的候選池大小？")
print()
print("建議策略：")
print()
print("```python")
print("def calculate_candidate_pool_size(category, people, budget):")
print("    '''")
print("    根據類別特性決定候選池大小")
print("    '''")
print("    base_sizes = {")
print("        '熱菜': 5,  # 熱菜選擇通常較多")
print("        '冷菜': 3,  # 冷菜選擇較少")
print("        '主食': 4,")
print("        '湯品': 3,")
print("        '點心': 4")
print("    }")
print("    ")
print("    base = base_sizes.get(category, 3)")
print("    ")
print("    # 根據人數調整（人越多，選擇越多）")
print("    if people >= 6:")
print("        base += 2")
print("    elif people >= 4:")
print("        base += 1")
print("    ")
print("    return base")
print("```")
print()

print("範例：")
print("  2人用餐 → 熱菜候選池 5 道")
print("  4人用餐 → 熱菜候選池 6 道")
print("  6人用餐 → 熱菜候選池 7 道")
print()

print("=" * 80)
print("🚨 邊界條件處理")
print("=" * 80)
print()

print("### 情境 1：候選池完全用完")
print()
print("```")
print("問題：使用者換了 10 次，所有候選都用完了")
print()
print("處理：")
print("  1. 顯示提示「該類別暫無更多推薦」")
print("  2. 提供選項：")
print("     - 「保留當前菜品」")
print("     - 「查看之前換掉的菜品」（回溯功能）")
print("```")
print()

print("### 情境 2：換菜後價格劇烈變化")
print()
print("```")
print("問題：從 $180 的菜換成 $350 的菜")
print()
print("處理：")
print("  1. 顯示價格差異警告「+$170 ⚠️」")
print("  2. 更新總價並檢查是否超預算")
print("  3. 如果超預算 >20%，彈出警告")
print("```")
print()

print("### 情境 3：候選池品質控制")
print()
print("```")
print("問題：候選池中有些菜的評分很低")
print()
print("處理：")
print("  1. 設定最低評分閾值（例如：3.5 星）")
print("  2. 過濾掉評分過低的菜品")
print("  3. 確保候選池中的菜都是「可推薦」的品質")
print("```")
print()

print("=" * 80)
print("✅ 總結：候選池設計原則")
print("=" * 80)
print()

print("1. ✅ 只推薦 AI 評估過的菜品（不是全菜單）")
print("2. ✅ 候選池大小適中（3-5 道備選）")
print("3. ✅ 混合策略（前端輪播 + API 補充）")
print("4. ✅ 價格範圍可控（候選池內價格應接近）")
print("5. ✅ 品質門檻（最低評分、評論數要求）")
print()

print("=" * 80)
print("📊 實際案例")
print("=" * 80)
print()

print("### 案例：鼎泰豐，2人用餐，預算 $1000")
print()
print("初始推薦：")
print("```")
print("冷菜（顯示）：涼拌黃瓜 $80")
print("  備選池：[皮蛋豆腐 $100, 泡菜 $60]")
print()
print("熱菜（顯示）：宮保雞丁 $180")
print("  備選池：[糖醋魚 $220, 紅燒肉 $280, 麻婆豆腐 $160, 魚香肉絲 $180]")
print()
print("主食（顯示）：蛋炒飯 $120")
print("  備選池：[揚州炒飯 $150, 白飯 $30, 炒麵 $130]")
print()
print("湯品（顯示）：酸辣湯 $100")
print("  備選池：[玉米濃湯 $90, 蛋花湯 $80]")
print()
print("點心（顯示）：小籠包 $200")
print("  備選池：[蝦餃 $180, 燒賣 $160, 鍋貼 $140]")
print("```")
print()

print("使用者操作：")
print("  1. 確定 涼拌黃瓜")
print("  2. 換掉 宮保雞丁 → 糖醋魚（從備選池）")
print("  3. 確定 蛋炒飯")
print("  4. 換掉 酸辣湯 → 玉米濃湯（從備選池）")
print("  5. 再換 玉米濃湯 → 蛋花湯（從備選池）")
print("  6. 再換 蛋花湯 → 呼叫 API（備選池用完）")
print()

print("=" * 80)
